extends Node

class FishObject:
	var Type
	var FishName
	var Speed
	var Scale
	var CurveAmplitude
	var CurveFrequency
	var TurnChance
	var LifeTime
	var BounceMultip
	
	func _init(type, fishName, speed, scale, curveAmplitude, curveFrequency, turnChance, lifeTime, bounceMultip) -> void:
		Type = type
		FishName = fishName
		Speed = speed
		Scale = scale
		CurveAmplitude = curveAmplitude
		CurveFrequency = curveFrequency
		TurnChance = turnChance
		LifeTime = lifeTime
		BounceMultip = bounceMultip

var Fish = {#						type,		name,												speed	scale	curveAmp	curveFrq.	turnChan.	LifeT.	BounceMultip
	FishEnum.Boot : FishObject.new(FishEnum.Boot,"Boot",											315,	0.9,	5,			0.1,		0.02,		8,		1.3),
	FishEnum.Seaweed : FishObject.new(FishEnum.Seaweed,"Seaweed",									434,	0.85,	10,			0.04,		0.04,		7,		1.38),
	FishEnum.ColaBottle : FishObject.new(FishEnum.ColaBottle,"Cola Bottle", 						377,	1.05,	25,			0.3,		0.06,		9,		1.45),
	FishEnum.Catfish : FishObject.new(FishEnum.Catfish,"Catfish",									515,	0.75,	35,			5,			0.05,		6,		1.51),
	FishEnum.GoldPotI : FishObject.new(FishEnum.GoldPotI,"Gold Pot I",								545,	0.76,	55,			0.09,		0.09,		6,		1.55),
	FishEnum.MagicPotI : FishObject.new(FishEnum.MagicPotI,"Magic Pot I",							570,	0.74,	80,			0.11,		0.11,		5.5,	1.52),
	FishEnum.StorageBox : FishObject.new(FishEnum.StorageBox,"Storage Box", 						699,	1.1,	30,			0.2,		0.17,		5,		1.39),
	
	FishEnum.GoldPotII : FishObject.new(FishEnum.GoldPotII,"Gold Pot II",							620,	0.75,	75,			0.65,		0.26,		5,		1.66),
	FishEnum.ElectricEal : FishObject.new(FishEnum.ElectricEal,"Electric Eal",						780,	0.85,	110,		3,			0.04,		6,		2.11),
	FishEnum.ElectricJellyfish : FishObject.new(FishEnum.ElectricJellyfish,"Electric Jellyfish",	900,	0.82,	135,		12,			0.005,		5,		2.55),
	
	FishEnum.MagicPotII : FishObject.new(FishEnum.MagicPotII,"Magic Pot II", 						650,	0.72,	100,		0.99,		0.0033,		4.5,	1.55),
	FishEnum.CrateFish : FishObject.new(FishEnum.CrateFish,"Crate Fish", 							401,	1.03,	66,			5,			0.3,		5,		1.45),
	FishEnum.AscentionFish : FishObject.new(FishEnum.AscentionFish,"Ascention Fish",				500,	1.06,	156,		5,			0.05,		5,		1.65),
	FishEnum.ElectricSponge : FishObject.new(FishEnum.ElectricSponge,"Electric Sponge", 			950,	0.75,	160,		46,			0.4,		4,		3.05),
	
	FishEnum.MagicPotIII : FishObject.new(FishEnum.MagicPotIII,"Magic Pot III", 					670,	0.69,	130,		6,			0.02,		3.5,	1.85),
	FishEnum.GoldPotIII : FishObject.new(FishEnum.GoldPotIII,"Gold Pot III", 						600,	0.73,	95,			4,			0.01,		4,		1.8),
	FishEnum.BigFish : FishObject.new(FishEnum.BigFish,"Big Fish", 									620,	1.2,	44,			3,			0.005,		4,		2),
	FishEnum.SpeedFish : FishObject.new(FishEnum.SpeedFish,"Speed Fish",							799,	1.03,	200,		33,			0.15,		6.6,	2),
	FishEnum.BaitFish : FishObject.new(FishEnum.BaitFish,"Bait Fish",								711,	0.87,	86,			1,			0.04,		5,		1.4),
	FishEnum.GoldFish : FishObject.new(FishEnum.GoldFish,"Gold Fish",								666,	0.69,	120,		7,			0.005,		5,		1.85),
	FishEnum.ConstructionShark : FishObject.new(FishEnum.ConstructionShark,"Bob The Shark",			545,	1.07,	93,			30,			0.23,		9,		1.7),
	FishEnum.LuckyFish : FishObject.new(FishEnum.LuckyFish,"Lucky Fish", 							777,	0.87,	77,			0.77,		0.77,		7,		2.5),
	
	FishEnum.Stick : FishObject.new(FishEnum.Stick,"Stick", 										499,	0.97,	23,			0.1,		0.001,		10,		1.25),
	FishEnum.MagicFish : FishObject.new(FishEnum.MagicFish,"Magic Fish",							655,	0.83,	150,		20,			0.055,		4,		1.9),
	FishEnum.WoodFish : FishObject.new(FishEnum.WoodFish,"Wood Fish",								345,	0.95,	40,			6,			0.3,		10,		2.1),
	FishEnum.BotFish : FishObject.new(FishEnum.BotFish,"Merchant Fish",									595,	0.72,	127,		35,			0.035,		4,		1.6),
	FishEnum.MultiplyingFish : FishObject.new(FishEnum.MultiplyingFish,"Multiplying Fish",			666,	0.65,	80,			14,			0.01,		4,		2.5),
	
	FishEnum.ResearchFish : FishObject.new(FishEnum.ResearchFish,"Research Fish",					422,	1.03,	66,			9,			0.0005,		4.3,	1.85),
	FishEnum.DamFish : FishObject.new(FishEnum.DamFish,"Dam Fish",									744,	1,		105,		5,			0.09,		7,		2.35),
	FishEnum.IceFish : FishObject.new(FishEnum.IceFish,"Ice Fish",									777,	1.06,	39,			15,			0.1,		7.8,	1.45),
	FishEnum.SalmonLumberJack : FishObject.new(FishEnum.SalmonLumberJack,"Salmon Lumber Jack",		490,	0.78,	76,			3,			0.01,		5.4,	1.95),
	FishEnum.Clownfish : FishObject.new(FishEnum.Clownfish,"Clownfish", 							515,	0.63,	170,		46,			0.07,		6,		3.3),
	FishEnum.DescentionFish : FishObject.new(FishEnum.DescentionFish,"Descention Fish", 			740,	0.85,	89,			23,			0.04,		4.6,	2.2),
	FishEnum.BlueWhale : FishObject.new(FishEnum.BlueWhale,"Blue Whale",							1190,	1.3,	75,			6,			0.01,		7,		3.5),
	
	FishEnum.OakCrate : FishObject.new(FishEnum.OakCrate,"Oak Crate",								300,	1.1,	55,			0.1,		0.1,		9.5,	1.35),
	FishEnum.AppleCrate : FishObject.new(FishEnum.AppleCrate,"Apple Crate", 						320,	1.07,	65,			0.8,		0.04,		9,		1.45),
	FishEnum.MapleCrate : FishObject.new(FishEnum.MapleCrate,"Maple Crate", 						345,	1.04,	75,			1.6,		0.1,		8.5,	1.55),
	FishEnum.BirchCrate : FishObject.new(FishEnum.BirchCrate,"Birch Crate", 						370,	1.01,	85,			3,			0.16,		8,		1.65),
	FishEnum.SpruceCrate : FishObject.new(FishEnum.SpruceCrate,"Spruce Crate",						395,	0.97,	95,			4.6,		0.35,		7.5,	1.75),
	FishEnum.ChestnutCrate : FishObject.new(FishEnum.ChestnutCrate,"Chestnut Crate", 				450,	0.95,	105,		6.6,		0.06,		7.2,	1.85),
	FishEnum.CherryCrate : FishObject.new(FishEnum.CherryCrate,"Cherry Crate",						505,	0.91,	115,		9.1,		0.99,		6.9,	1.95),
	FishEnum.AshCrate : FishObject.new(FishEnum.AshCrate,"Ash Crate",								560,	0.86,	125,		10,			0.2,		6.6,	2.05),
	FishEnum.CedarCrate : FishObject.new(FishEnum.CedarCrate,"Cedar Crate", 						615,	0.82,	135,		12,			0.29,		6.3,	2.15),
	FishEnum.MahoganyCrate : FishObject.new(FishEnum.MahoganyCrate,"Mahogany Crate", 				670,	0.78,	145,		14,			0.55,		6,		2.25),
	FishEnum.EbonyCrate : FishObject.new(FishEnum.EbonyCrate,"Ebony Crate", 						725,	0.75,	155,		16,			0.99,		5.7,	2.35),
	FishEnum.DogwoodCrate : FishObject.new(FishEnum.DogwoodCrate,"Dogwood Crate",					780,	0.72,	165,		19,			0.19,		5.4,	2.45),
	FishEnum.RosewoodCrate : FishObject.new(FishEnum.RosewoodCrate,"Rosewood Crate",				835,	0.69,	175,		24,			0.77,		5,		2.55),
	FishEnum.GhostGumCrate : FishObject.new(FishEnum.GhostGumCrate,"Ghost Gum Crate",				890,	0.66,	185,		35,			0.2,		4.6,	2.65),
	FishEnum.DragonwoodCrate : FishObject.new(FishEnum.DragonwoodCrate,"Dragonwood Crate",			1100,	0.63,	195,		45,			0.6,		4.2,	2.75),
}

var FishPrice = {
	FishEnum.Boot :  5,
	FishEnum.Seaweed : 8,
	FishEnum.ColaBottle : 15,
	FishEnum.Catfish : 25,
	FishEnum.GoldPotI : 45,
	FishEnum.MagicPotI : 35,
	FishEnum.StorageBox : 40,
	
	FishEnum.GoldPotII : 90,
	FishEnum.ElectricEal : 380,
	FishEnum.ElectricJellyfish : 500,
	
	FishEnum.MagicPotII : 190,
	FishEnum.CrateFish : 325,
	FishEnum.AscentionFish : 420,
	FishEnum.ElectricSponge : 2500,
	
	FishEnum.MagicPotIII : 400,
	FishEnum.GoldPotIII : 550,
	FishEnum.BigFish : 500,
	FishEnum.SpeedFish : 750,
	FishEnum.BaitFish : 666,
	FishEnum.GoldFish : 1000,
	FishEnum.ConstructionShark : 1111,
	FishEnum.LuckyFish : 15000,
	
	FishEnum.Stick : 400,
	FishEnum.MagicFish : 1900,
	FishEnum.WoodFish : 3730,
	FishEnum.BotFish : 5100,
	FishEnum.MultiplyingFish : 8500,
	
	FishEnum.ResearchFish : 2750,
	FishEnum.DamFish : 5200,
	FishEnum.IceFish : 7000,
	FishEnum.SalmonLumberJack : 9999,
	FishEnum.Clownfish : 15000,
	FishEnum.DescentionFish : 32000,
	FishEnum.BlueWhale : 50000,
	
	
	FishEnum.OakCrate : 15,
	
	FishEnum.AppleCrate : 45,
	FishEnum.MapleCrate : 65,
	FishEnum.BirchCrate : 85,
	FishEnum.SpruceCrate : 105,
	
	FishEnum.ChestnutCrate : 350,
	FishEnum.CherryCrate : 400,
	FishEnum.AshCrate : 450,
	
	FishEnum.CedarCrate : 1000,
	FishEnum.MahoganyCrate : 1200,
	
	FishEnum.EbonyCrate : 3000,
	FishEnum.DogwoodCrate : 4000,
	FishEnum.RosewoodCrate : 5000,
	
	FishEnum.GhostGumCrate : 13000,
	FishEnum.DragonwoodCrate : 18000,
}

var FishLevel = {
	FishEnum.Boot :  0,
	FishEnum.Seaweed : 0,
	FishEnum.ColaBottle : 0,
	FishEnum.Catfish : 0,
	FishEnum.GoldPotI : 0,
	FishEnum.MagicPotI : 0,
	FishEnum.StorageBox : 0,
	
	FishEnum.GoldPotII : 1,
	FishEnum.ElectricEal : 1,
	FishEnum.ElectricJellyfish : 1,
	
	FishEnum.MagicPotII : 2,
	FishEnum.CrateFish : 2,
	FishEnum.AscentionFish : 2,
	FishEnum.ElectricSponge : 2,
	
	FishEnum.MagicPotIII : 3,
	FishEnum.GoldPotIII : 3,
	FishEnum.BigFish : 3,
	FishEnum.SpeedFish : 3,
	FishEnum.BaitFish : 3,
	FishEnum.GoldFish : 3,
	FishEnum.ConstructionShark : 3,
	FishEnum.LuckyFish : 3,
	
	FishEnum.Stick : 4,
	FishEnum.MagicFish : 4,
	FishEnum.WoodFish : 4,
	FishEnum.BotFish : 4,
	FishEnum.MultiplyingFish : 4,
	
	FishEnum.ResearchFish : 5,
	FishEnum.DamFish : 5,
	FishEnum.IceFish : 5,
	FishEnum.SalmonLumberJack : 5,
	FishEnum.Clownfish : 5,
	FishEnum.DescentionFish : 5,
	FishEnum.BlueWhale : 5,
	
	
	FishEnum.OakCrate : 0,
	
	FishEnum.AppleCrate : 1,
	FishEnum.MapleCrate : 1,
	FishEnum.BirchCrate : 1,
	FishEnum.SpruceCrate : 1,
	
	FishEnum.ChestnutCrate : 2,
	FishEnum.CherryCrate : 2,
	FishEnum.AshCrate : 2,
	
	FishEnum.CedarCrate : 3,
	FishEnum.MahoganyCrate : 3,
	
	FishEnum.EbonyCrate : 4,
	FishEnum.DogwoodCrate : 4,
	FishEnum.RosewoodCrate : 4,
	
	FishEnum.GhostGumCrate : 5,
	FishEnum.DragonwoodCrate : 5,
}

var FishRarity = {
	FishEnum.Boot :  44,
	FishEnum.Seaweed : 38,
	FishEnum.ColaBottle : 33,
	FishEnum.Catfish : 30,
	FishEnum.GoldPotI : 25,
	FishEnum.MagicPotI : 22,
	FishEnum.StorageBox : 10,
	
	FishEnum.GoldPotII : 20,
	FishEnum.ElectricEal : 6,
	FishEnum.ElectricJellyfish : 4,
	
	FishEnum.MagicPotII : 17,
	FishEnum.CrateFish : 25,
	FishEnum.AscentionFish : 15,
	FishEnum.ElectricSponge : 4,
	
	FishEnum.MagicPotIII : 12,
	FishEnum.GoldPotIII : 15,
	FishEnum.BigFish : 33,
	FishEnum.SpeedFish : 12,
	FishEnum.BaitFish : 12,
	FishEnum.GoldFish : 5,
	FishEnum.ConstructionShark : 7,
	FishEnum.LuckyFish : 4,
	
	FishEnum.Stick : 40,
	FishEnum.MagicFish : 5,
	FishEnum.WoodFish : 30,
	FishEnum.BotFish : 40,
	FishEnum.MultiplyingFish : 15,
	
	FishEnum.ResearchFish : 15,
	FishEnum.DamFish : 16,
	FishEnum.IceFish : 19,
	FishEnum.SalmonLumberJack : 7,
	FishEnum.Clownfish : 26,
	FishEnum.DescentionFish : 25,
	FishEnum.BlueWhale : 5,
	
	FishEnum.OakCrate : 17,
	FishEnum.AppleCrate : 17,
	FishEnum.MapleCrate : 17,
	FishEnum.BirchCrate : 17,
	FishEnum.SpruceCrate : 17,
	FishEnum.ChestnutCrate : 17,
	FishEnum.CherryCrate : 17,
	FishEnum.AshCrate : 17,
	FishEnum.CedarCrate : 17,
	FishEnum.MahoganyCrate : 17,
	FishEnum.EbonyCrate : 17,
	FishEnum.DogwoodCrate : 17,
	FishEnum.RosewoodCrate : 17,
	FishEnum.GhostGumCrate : 17,
	FishEnum.DragonwoodCrate : 17,
}

var FishEffect = {
	FishEnum.Boot :  "1% Wood Per Second",
	FishEnum.Seaweed : "1% Wood Per Click",
	FishEnum.ColaBottle : "1% Storage",
	FishEnum.Catfish : "+1 Beaver",
	FishEnum.GoldPotI : "1% Wood Price",
	FishEnum.GoldPotII : "2.5% Wood Price",
	FishEnum.GoldPotIII : "5% Wood Price",
	FishEnum.GoldFish : "3% Cheaper Gold Upgrades",
	FishEnum.MagicPotI : "1% Magic Gain",
	FishEnum.MagicPotII : "2% Magic Gain",
	FishEnum.MagicPotIII : "3% Magic Gain",
	FishEnum.MagicFish : "5% Magic Gain",
	FishEnum.SpeedFish : "3% Lower Fish Speed",
	FishEnum.StorageBox : "+25 Woodcamp Base Storage",
	FishEnum.ResearchFish : "1% Faster Research",
	FishEnum.WoodFish : "2% Wood Price",
	FishEnum.DamFish : "3% Dam Effect",
	FishEnum.LuckyFish : "1.5% Fish Price and Fish Effects",
	FishEnum.CrateFish : "+30 Beaver Storage",
	FishEnum.BotFish : "1% Cheaper Merchants",
	FishEnum.IceFish : "1% Lower Fish Bounce",
	FishEnum.BaitFish : "+1 Bait Count In Shop",
	FishEnum.ElectricEal : "5% Longer Fishing Time",
	FishEnum.ElectricJellyfish : "3% Longer Fish Lifespan",
	FishEnum.ElectricSponge : "-1% Chance To Consume Bait",
	FishEnum.ConstructionShark : "-1% Woodcamp Wood Cost",
	FishEnum.SalmonLumberJack : "1% Woodcamp Effect",
	FishEnum.AscentionFish : "3% More Magic On Ascention",
	FishEnum.DescentionFish : "0.001% Magic Per Second",
	FishEnum.BigFish : "2% Bigger Fish",
	FishEnum.Clownfish : "+1 Woodcamp (Clownfish = Woodcamp)",
	FishEnum.Stick : "2% Wood Per Second",
	FishEnum.OakCrate : "2.5% Oak WPS, WPC and Storage",
	FishEnum.AppleCrate : "2.5% Apple WPS, WPC and Storage",
	FishEnum.MapleCrate : "2.5% Maple WPS, WPC and Storage",
	FishEnum.BirchCrate : "2.5% Birch WPS, WPC and Storage",
	FishEnum.SpruceCrate : "2.5% Spruce WPS, WPC and Storage",
	FishEnum.ChestnutCrate : "2.5% Chestnut WPS, WPC and Storage",
	FishEnum.CherryCrate : "2.5% Cherry WPS, WPC and Storage",
	FishEnum.AshCrate : "2.5% Ash WPS, WPC and Storage",
	FishEnum.CedarCrate : "2.5% Cedar WPS, WPC and Storage",
	FishEnum.MahoganyCrate : "2.5% Mahogany WPS, WPC and Storage",
	FishEnum.EbonyCrate : "2.5% Ebony WPS, WPC and Storage",
	FishEnum.DogwoodCrate : "2.5% Dogwood WPS, WPC and Storage",
	FishEnum.RosewoodCrate : "2.5% Rosewood WPS, WPC and Storage",
	FishEnum.GhostGumCrate : "2.5% Ghost Gum WPS, WPC and Storage",
	FishEnum.DragonwoodCrate : "2.5% Dragonwood WPS, WPC and Storage",
	FishEnum.BlueWhale : "3% WPS, WPC and Storage",
	FishEnum.MultiplyingFish : "3% More Fish Appear",
}

enum ShopItemEnum {
	NoBait,
	Worm,
	Cricket,
	Jig,
	Leech,
	WyvernsFeather,
	Autoclicker1,
	Autoclicker2,
	Autoclicker3,
	WpsBonus1,
	WpsBonus2,
	WpsBonus3,
	WpcBonus1,
	WpcBonus2,
	WpcBonus3,
	WpsIncrease,
	WpcIncrease,
	StorageIncrease,
	ResearchSlot,
	FishingChance1,
	FishingChance2,
	ChanceToUseBait,
	FishingClick1,
	ChanceRefresh1,
	ChanceRefresh2,
	FishingChance3,
	FishingClick2,
	FishingTime1,
	FishingTime2,
	RefundChance1,
	RefundChance2,
}

var ShopItems = {
	ShopItemEnum.Worm : {
		"Name" : "Worm",
		"Description" : "Worm",
		"Price" : 30,
		"UnlockPrice" : 75,
		"FishingPower" : 1,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Cricket : {
		"Name" : "Cricket",
		"Description" : "Cricket",
		"Price" : 250,
		"UnlockPrice" : 350,
		"FishingPower" : 2,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Jig : {
		"Name" : "Jig",
		"Description" : "Jig",
		"Price" : 1000,
		"UnlockPrice" : 1750,
		"FishingPower" : 3,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Leech : {
		"Name" : "Leech",
		"Description" : "Leech",
		"Price" : 3500,
		"UnlockPrice" : 7500,
		"FishingPower" : 4,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.WyvernsFeather : {
		"Name" : "Wyverns Feather",
		"Description" : "Wyverns Feather",
		"Price" : 10000,
		"UnlockPrice" : 30000,
		"FishingPower" : 5,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Autoclicker1 : {
		"Name" : "+1 Autoclicker",
		"Description" : "Add another Autoclicker",
		"Price" : 2000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.Autoclicker2 : {
		"Name" : "+1 Autoclicker",
		"Description" : "Add another Autoclicker",
		"Price" : 15000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.Autoclicker3 : {
		"Name" : "+1 Autoclicker",
		"Description" : "Add another Autoclicker",
		"Price" : 125000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsBonus1 : {
		"Name" : "WPS Bonus 1",
		"Description" : "10% Wood Per Second Bonus For 10 minutes",
		"Price" : 250,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpcBonus1 : {
		"Name" : "WPC Bonus 1",
		"Description" : "30% Wood Per Click Bonus For 10 minutes",
		"Price" : 250,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsBonus2 : {
		"Name" : "WPS Bonus 2",
		"Description" : "20% Wood Per Second Bonus For 20 minutes",
		"Price" : 4000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpcBonus2 : {
		"Name" : "WPC Bonus 2",
		"Description" : "60% Wood Per Click Bonus For 20 minutes",
		"Price" : 4000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsBonus3 : {
		"Name" : "WPS Bonus 3",
		"Description" : "30% Wood Per Second Bonus For 30 minutes",
		"Price" : 20000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpcBonus3 : {
		"Name" : "WPC Bonus 3",
		"Description" : "90% Wood Per Click Bonus For 30 minutes",
		"Price" : 20000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsIncrease : {
		"Name" : "Increase WPS",
		"Description" : "Increase Wood Per Second By 1%",
		"Price" : 5,
		"IsBait" : false,
		"HasCount" : true,
	},
	ShopItemEnum.WpcIncrease : {
		"Name" : "Increase WPC",
		"Description" : "Increase Wood Per Click By 1%",
		"Price" : 7,
		"IsBait" : false,
		"HasCount" : true,
	},
	ShopItemEnum.StorageIncrease : {
		"Name" : "Increase Storage",
		"Description" : "Increase Storage By 1%",
		"Price" : 10,
		"IsBait" : false,
		"HasCount" : true,
	},
	ShopItemEnum.ChanceToUseBait : {
		"Name" : "Lower Bait Use",
		"Description" : "Lower Chance Bait Is Used By 10%",
		"Price" : 100,
		"IsBait" : false,
		"HasCount" : true,
	},
	ShopItemEnum.ResearchSlot : {
		"Name" : "+1 Research Slot",
		"Description" : "Add another Research Slot",
		"Price" : 5500,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingChance1 : {
		"Name" : "+1 Fishing Chance",
		"Description" : "Add another Fishing Chance",
		"Price" : 135,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingChance2 : {
		"Name" : "+1 Fishing Chance",
		"Description" : "Add another Fishing Chance",
		"Price" : 8000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingChance3 : {
		"Name" : "+1 Fishing Chance",
		"Description" : "Add another Fishing Chance",
		"Price" : 35750,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingClick1 : {
		"Name" : "+1 Fishing Click",
		"Description" : "+1 Chance To Click on Fish Before Failing When Fishing",
		"Price" : 220,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingClick2 : {
		"Name" : "+1 Fishing Click",
		"Description" : "+1 Chance To Click on Fish Before Failing When Fishing",
		"Price" : 1600,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.ChanceRefresh1 : {
		"Name" : "Fishing Chance -1 min",
		"Description" : "Lowers Fishing Chance Refresh Time By 1 minute",
		"Price" : 6500,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.ChanceRefresh2 : {
		"Name" : "Fishing Chance -1 min",
		"Description" : "Lowers Fishing Chance Refresh Time By 1 minute",
		"Price" : 65000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingTime1 : {
		"Name" : "+5 sec fishing time",
		"Description" : "Increases Time For Fishing By 5 Seconds",
		"Price" : 50,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingTime2 : {
		"Name" : "+5 sec fishing time",
		"Description" : "Increases Time For Fishing By 5 Seconds",
		"Price" : 850,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.RefundChance1 : {
		"Name" : "+15% Refund Chance",
		"Description" : "15% Bigger Chance To Refund A Fishing Chance When Failing To Catch A Fish",
		"Price" : 4500,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.RefundChance2 : {
		"Name" : "+15% Refund Chance",
		"Description" : "15% Bigger Chance To Refund A Fishing Chance When Failing To Catch A Fish",
		"Price" : 20000,
		"IsBait" : false,
		"HasCount" : false,
	},
}

enum FishEnum {
	Boot,
	Seaweed,
	ColaBottle,
	Catfish,
	GoldPotI,
	GoldPotII,
	GoldPotIII,
	GoldFish,
	MagicPotI,
	MagicPotII,
	MagicPotIII,
	MagicFish,
	SpeedFish,
	StorageBox,
	ResearchFish,
	WoodFish,
	DamFish,
	LuckyFish,
	CrateFish,
	BotFish,
	IceFish,
	BaitFish,
	ElectricEal,
	ElectricJellyfish,
	ElectricSponge,
	ConstructionShark,
	SalmonLumberJack,
	AscentionFish,
	DescentionFish,
	BigFish,
	Clownfish,
	Stick,
	OakCrate,
	AppleCrate,
	MapleCrate,
	BirchCrate,
	SpruceCrate,
	ChestnutCrate,
	CherryCrate,
	AshCrate,
	CedarCrate,
	MahoganyCrate,
	EbonyCrate,
	DogwoodCrate,
	RosewoodCrate,
	GhostGumCrate,
	DragonwoodCrate,
	BlueWhale,
	MultiplyingFish,
}
