extends Node

var Spots

class FishObject:
	var Type
	var Name
	var Speed
	var Size
	var Angle
	var LifeTime
	var BounceSpeed
	var SellsFor
	var SellCount
	
	func _init(type, name, speed, size, angle, lifeTime, bounceSpeed) -> void:
		Type = type
		Name = name
		Speed = speed
		Size = size
		Angle = angle
		LifeTime = lifeTime
		BounceSpeed = bounceSpeed

var Fish = { # type, name, speed, size, angle, lifeTime
	FishEnum.Boot : FishObject.new(FishEnum.Boot,"Boot", 0.5, 3, 0.6, 10, 10),
	FishEnum.Seaweed : FishObject.new(FishEnum.Seaweed,"Seaweed", 0.4, 2.4, 0.8, 9, 9),
	FishEnum.ColaBottle : FishObject.new(FishEnum.ColaBottle,"Cola Bottle", 0.7, 2, 0.6, 8, 8),
	FishEnum.Catfish : FishObject.new(FishEnum.Catfish,"Catfish", 1.5, 1.7, 1.1, 5, 5),
	FishEnum.GoldPotI : FishObject.new(FishEnum.GoldPotI,"Gold Pot I", 1, 3, 0.6, 9, 9),
	FishEnum.GoldPotII : FishObject.new(FishEnum.GoldPotII,"Gold Pot II", 2, 2, 1.2, 5, 5),
	FishEnum.GoldPotIII : FishObject.new(FishEnum.GoldPotIII,"Gold Pot III", 3, 1, 2.4, 2, 2),
	FishEnum.GoldFish : FishObject.new(FishEnum.GoldFish,"Gold Fish", 0.4, 3, 0.6, 7, 2),
	FishEnum.MagicPotI : FishObject.new(FishEnum.MagicPotI,"Magic Pot I", 0.4, 3, 0.6, 7, 2),
	FishEnum.MagicPotII : FishObject.new(FishEnum.MagicPotII,"Magic Pot II", 0.4, 3, 0.6, 3, 2),
	FishEnum.MagicPotIII : FishObject.new(FishEnum.MagicPotIII,"Magic Pot III", 0.4, 3, 0.6, 1, 2),
	FishEnum.MagicFish : FishObject.new(FishEnum.MagicFish,"Magic Fish", 0.4, 3, 0.6, 0.6, 2),
	FishEnum.SpeedFish : FishObject.new(FishEnum.SpeedFish,"Speed Fish", 0.4, 3, 0.6, 0.8, 2),
	FishEnum.StorageBox : FishObject.new(FishEnum.StorageBox,"Storage Box", 0.4, 3, 0.6, 5, 5),
	FishEnum.ResearchFish : FishObject.new(FishEnum.ResearchFish,"Research Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.WoodFish : FishObject.new(FishEnum.WoodFish,"Wood Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.DamFish : FishObject.new(FishEnum.DamFish,"Dam Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.LuckyFish : FishObject.new(FishEnum.LuckyFish,"Lucky Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.CrateFish : FishObject.new(FishEnum.CrateFish,"Crate Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.BotFish : FishObject.new(FishEnum.BotFish,"Bot Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.IceFish : FishObject.new(FishEnum.IceFish,"Ice Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.BaitFish : FishObject.new(FishEnum.BaitFish,"Bait Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.ElectricEal : FishObject.new(FishEnum.ElectricEal,"Electric Eal", 0.4, 3, 0.6, 5, 5),
	FishEnum.ElectricJellyfish : FishObject.new(FishEnum.ElectricJellyfish,"Electric Jellyfish", 0.4, 3, 0.6, 5, 5),
	FishEnum.ElectricSponge : FishObject.new(FishEnum.ElectricSponge,"Electric Sponge", 0.4, 3, 0.6, 5, 5),
	FishEnum.ConstructionShark : FishObject.new(FishEnum.ConstructionShark,"Construction Shark", 0.4, 3, 0.6, 5, 5),
	FishEnum.SalmonLumberJack : FishObject.new(FishEnum.SalmonLumberJack,"Salmon Lumber Jack", 0.4, 3, 0.6, 5, 5),
	FishEnum.AscentionFish : FishObject.new(FishEnum.AscentionFish,"Ascention Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.DescentionFish : FishObject.new(FishEnum.DescentionFish,"Descention Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.BigFish : FishObject.new(FishEnum.BigFish,"Big Fish", 0.4, 3, 0.6, 5, 5),
	FishEnum.Clownfish : FishObject.new(FishEnum.Clownfish,"Clownfish", 0.4, 3, 0.6, 5, 5),
	FishEnum.Stick : FishObject.new(FishEnum.Stick,"Stick", 0.4, 3, 0.6, 5, 5),
	FishEnum.OakCrate : FishObject.new(FishEnum.OakCrate,"Oak Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.AppleCrate : FishObject.new(FishEnum.AppleCrate,"Apple Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.MapleCrate : FishObject.new(FishEnum.MapleCrate,"Maple Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.BirchCrate : FishObject.new(FishEnum.BirchCrate,"Birch Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.SpruceCrate : FishObject.new(FishEnum.SpruceCrate,"Spruce Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.ChestnutCrate : FishObject.new(FishEnum.ChestnutCrate,"Chestnut Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.CherryCrate : FishObject.new(FishEnum.CherryCrate,"Cherry Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.AshCrate : FishObject.new(FishEnum.AshCrate,"Ash Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.CedarCrate : FishObject.new(FishEnum.CedarCrate,"Cedar Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.MahoganyCrate : FishObject.new(FishEnum.MahoganyCrate,"Mahogany Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.EbonyCrate : FishObject.new(FishEnum.EbonyCrate,"Ebony Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.DogwoodCrate : FishObject.new(FishEnum.DogwoodCrate,"Dogwood Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.RosewoodCrate : FishObject.new(FishEnum.RosewoodCrate,"Rosewood Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.GhostGumCrate : FishObject.new(FishEnum.GhostGumCrate,"Ghost Gum Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.DragonwoodCrate : FishObject.new(FishEnum.DragonwoodCrate,"Dragonwood Crate", 0.4, 3, 0.6, 5, 5),
	FishEnum.BlueWhale : FishObject.new(FishEnum.BlueWhale,"Blue Whale", 0.4, 3, 0.6, 5, 5),
	FishEnum.MultiplyingFish : FishObject.new(FishEnum.MultiplyingFish,"Multiplying Fish", 0.4, 3, 0.6, 5, 5),
}

var FishPrice = {
	FishEnum.Boot :  0.1,
	FishEnum.Seaweed : 0.125,
	FishEnum.ColaBottle : 0.2,
	FishEnum.Catfish : 1,
	FishEnum.GoldPotI : 3,
	FishEnum.GoldPotII : 18,
	FishEnum.GoldPotIII : 60,
	FishEnum.GoldFish : 230,
	FishEnum.MagicPotI : 5,
	FishEnum.MagicPotII : 75,
	FishEnum.MagicPotIII : 300,
	FishEnum.MagicFish : 800,
	FishEnum.SpeedFish : 660,
	FishEnum.StorageBox : 2,
	FishEnum.ResearchFish : 1750,
	FishEnum.WoodFish : 730,
	FishEnum.DamFish : 3200,
	FishEnum.LuckyFish : 260,
	FishEnum.CrateFish : 125,
	FishEnum.BotFish : 1200,
	FishEnum.IceFish : 2200,
	FishEnum.BaitFish : 160,
	FishEnum.ElectricEal : 20,
	FishEnum.ElectricJellyfish : 40,
	FishEnum.ElectricSponge : 90,
	FishEnum.ConstructionShark : 77,
	FishEnum.SalmonLumberJack : 1000,
	FishEnum.AscentionFish : 25,
	FishEnum.DescentionFish : 2230,
	FishEnum.BigFish : 89,
	FishEnum.Clownfish : 4400,
	FishEnum.Stick : 555,
	FishEnum.OakCrate : 1,
	FishEnum.AppleCrate : 3,
	FishEnum.MapleCrate : 6,
	FishEnum.BirchCrate : 10,
	FishEnum.SpruceCrate : 14,
	FishEnum.ChestnutCrate : 19,
	FishEnum.CherryCrate : 24,
	FishEnum.AshCrate : 30,
	FishEnum.CedarCrate : 36,
	FishEnum.MahoganyCrate : 43,
	FishEnum.EbonyCrate : 55,
	FishEnum.DogwoodCrate : 70,
	FishEnum.RosewoodCrate : 90,
	FishEnum.GhostGumCrate : 120,
	FishEnum.DragonwoodCrate : 200,
	FishEnum.BlueWhale : 1100,
	FishEnum.MultiplyingFish : 600,
}

enum BaitEnum {
	NoBait,
	Leaf,
	Worm,
	Jig,
	Cricket,
	Catarpiller,
	Leech,
	CrateAtractor,
	GiantSquidsTentacle,
	WyvernsFeather,
	DevilsTongue,
	ShinyWorm,
}

var Bait = {
	BaitEnum.NoBait : {
		"Name" : "No Bait",
		"Price" : 0,
		"Effect" : 0,
	},
	BaitEnum.Leaf : {
		"Name" : "Leaf",
		"Price" : 1000,
		"Effect" : 5,
	},
	BaitEnum.Worm : {
		"Name" : "Worm",
		"Price" : 15000,
		"Effect" : 10,
	},
	BaitEnum.Jig : {
		"Name" : "Jig",
		"Price" : 175000,
		"Effect" : 20,
	},
	BaitEnum.Cricket : {
		"Name" : "Cricket",
		"Price" : 2000000,
		"Effect" : 35,
	},
	BaitEnum.Catarpiller : {
		"Name" : "Catarpiller",
		"Price" : 25000000,
		"Effect" : 55,
	},
	BaitEnum.Leech : {
		"Name" : "Leech",
		"Price" : 300000000,
		"Effect" : 80,
	},
	BaitEnum.CrateAtractor : {
		"Name" : "Crate Atractor",
		"Price" : 500000000,
		"Effect" : 100,
	},
	BaitEnum.GiantSquidsTentacle : {
		"Name" : "G. S. Tentacle",
		"Price" : 4000000000,
		"Effect" : 110,
	},
	BaitEnum.WyvernsFeather : {
		"Name" : "Wyverns Feather",
		"Price" : 45000000000,
		"Effect" : 145,
	},
	BaitEnum.DevilsTongue : {
		"Name" : "Devils Tongue",
		"Price" : 500000000000,
		"Effect" : 185,
	},
	BaitEnum.ShinyWorm : {
		"Name" : "Shiny Worm",
		"Price" : 6000000000000,
		"Effect" : 230,
	},
}

enum FishEnum {
	Boot,
	Seaweed,
	ColaBottle,
	Catfish,
	GoldPotI,
	GoldPotII,
	GoldPotIII,
	GoldFish,
	MagicPotI,
	MagicPotII,
	MagicPotIII,
	MagicFish,
	SpeedFish,
	StorageBox,
	ResearchFish,
	WoodFish,
	DamFish,
	LuckyFish,
	CrateFish,
	BotFish,
	IceFish,
	BaitFish,
	ElectricEal,
	ElectricJellyfish,
	ElectricSponge,
	ConstructionShark,
	SalmonLumberJack,
	AscentionFish,
	DescentionFish,
	BigFish,
	Clownfish,
	Stick,
	OakCrate,
	AppleCrate,
	MapleCrate,
	BirchCrate,
	SpruceCrate,
	ChestnutCrate,
	CherryCrate,
	AshCrate,
	CedarCrate,
	MahoganyCrate,
	EbonyCrate,
	DogwoodCrate,
	RosewoodCrate,
	GhostGumCrate,
	DragonwoodCrate,
	BlueWhale,
	MultiplyingFish,
}
