extends Node

var Spots

class FishObject:
	var Type
	var FishName
	var Speed
	var Scale
	var CurveAmplitude
	var CurveFrequency
	var TurnChance
	var LifeTime
	var BounceSpeed
	var SellsFor
	var SellCount
	
	func _init(type, fishName, speed, scale, curveAmplitude, curveFrequency, turnChance, lifeTime) -> void:
		Type = type
		FishName = fishName
		Speed = speed
		Scale = scale
		CurveAmplitude = curveAmplitude
		CurveFrequency = curveFrequency
		TurnChance = turnChance
		LifeTime = lifeTime

var Fish = { # type, name, 				speed, scale, curveAmplitude, curveFrequency, turnChance, LifeTime
	FishEnum.Boot : FishObject.new(FishEnum.Boot,"Boot",											205, 1, 15, 0.1, 0.00001, 8),
	FishEnum.Seaweed : FishObject.new(FishEnum.Seaweed,"Seaweed",									344, 0.9, 10, 0.04, 0.00002, 7),
	FishEnum.ColaBottle : FishObject.new(FishEnum.ColaBottle,"Cola Bottle", 						267, 1.2, 25, 0.3, 0.00006, 9),
	FishEnum.Catfish : FishObject.new(FishEnum.Catfish,"Catfish",									465, 0.8, 35, 5, 0.0005, 6),
	FishEnum.GoldPotI : FishObject.new(FishEnum.GoldPotI,"Gold Pot I",								535, 0.75, 55, 0.09, 0.00009, 6),
	FishEnum.GoldPotII : FishObject.new(FishEnum.GoldPotII,"Gold Pot II",							600, 0.7, 75, 0.65, 0.00026, 5),
	FishEnum.GoldPotIII : FishObject.new(FishEnum.GoldPotIII,"Gold Pot III", 						700, 0.65, 95, 4, 0.001, 4),
	FishEnum.GoldFish : FishObject.new(FishEnum.GoldFish,"Gold Fish",								666, 0.77, 120, 7, 0.0005, 5),
	FishEnum.MagicPotI : FishObject.new(FishEnum.MagicPotI,"Magic Pot I",							370, 0.74, 80, 0.11, 0.00011, 5.5),
	FishEnum.MagicPotII : FishObject.new(FishEnum.MagicPotII,"Magic Pot II", 						550, 0.68, 100, 0.99, 0.00033, 4.5),
	FishEnum.MagicPotIII : FishObject.new(FishEnum.MagicPotIII,"Magic Pot III", 					870, 0.62, 130, 6, 0.002, 3.5),
	FishEnum.MagicFish : FishObject.new(FishEnum.MagicFish,"Magic Fish",							655, 0.88, 150, 20, 0.00055, 4),
	FishEnum.SpeedFish : FishObject.new(FishEnum.SpeedFish,"Speed Fish",							999, 1.5, 200, 33, 0.005, 6.6),
	FishEnum.StorageBox : FishObject.new(FishEnum.StorageBox,"Storage Box", 						399, 1.2, 30, 0.2, 0.0007, 5),
	FishEnum.ResearchFish : FishObject.new(FishEnum.ResearchFish,"Research Fish",					222, 1.3, 66, 9, 0.00005, 4.3),
	FishEnum.WoodFish : FishObject.new(FishEnum.WoodFish,"Wood Fish",								145, 1.1, 40, 6, 0.03, 10),
	FishEnum.DamFish : FishObject.new(FishEnum.DamFish,"Dam Fish",									804, 2, 105, 5, 0.009, 7),
	FishEnum.LuckyFish : FishObject.new(FishEnum.LuckyFish,"Lucky Fish", 							777, 1.7, 77, 0.77, 0.77, 7),
	FishEnum.CrateFish : FishObject.new(FishEnum.CrateFish,"Crate Fish", 							301, 1.3, 66, 5, 0.5, 5),
	FishEnum.BotFish : FishObject.new(FishEnum.BotFish,"Bot Fish",									495, 0.99, 127, 35, 0.0035, 4),
	FishEnum.IceFish : FishObject.new(FishEnum.IceFish,"Ice Fish",									877, 1.25, 39, 15, 0.00001, 7.8),
	FishEnum.BaitFish : FishObject.new(FishEnum.BaitFish,"Bait Fish",								811, 1, 86, 1, 0.004, 5),
	FishEnum.ElectricEal : FishObject.new(FishEnum.ElectricEal,"Electric Eal",						1050, 0.95, 110, 3, 0.004, 6),
	FishEnum.ElectricJellyfish : FishObject.new(FishEnum.ElectricJellyfish,"Electric Jellyfish",	1200, 0.85, 135, 12, 0.04, 5),
	FishEnum.ElectricSponge : FishObject.new(FishEnum.ElectricSponge,"Electric Sponge", 			1350, 0.75, 160, 46, 0.4, 4),
	FishEnum.ConstructionShark : FishObject.new(FishEnum.ConstructionShark,"Construction Shark",	645, 1.7, 93, 30, 0.00023, 9),
	FishEnum.SalmonLumberJack : FishObject.new(FishEnum.SalmonLumberJack,"Salmon Lumber Jack",		400, 0.87, 76, 3, 0.0001, 5.4),
	FishEnum.AscentionFish : FishObject.new(FishEnum.AscentionFish,"Ascention Fish",				500, 1.45, 156, 5, 0.005, 5),
	FishEnum.DescentionFish : FishObject.new(FishEnum.DescentionFish,"Descention Fish", 			600, 1.1, 89, 23, 0.0004, 4.6),
	FishEnum.BigFish : FishObject.new(FishEnum.BigFish,"Big Fish", 									620, 3, 44, 3, 0.00005, 4),
	FishEnum.Clownfish : FishObject.new(FishEnum.Clownfish,"Clownfish", 							275, 0.78, 170, 46, 0.007, 6),
	FishEnum.Stick : FishObject.new(FishEnum.Stick,"Stick", 										99, 1.3, 23, 0.1, 0.00001, 10),
	FishEnum.OakCrate : FishObject.new(FishEnum.OakCrate,"Oak Crate",								200, 1.35, 55, 0.1, 0.00001, 9.5),
	FishEnum.AppleCrate : FishObject.new(FishEnum.AppleCrate,"Apple Crate", 						250, 1.3, 65, 0.8, 0.00004, 9),
	FishEnum.MapleCrate : FishObject.new(FishEnum.MapleCrate,"Maple Crate", 						300, 1.25, 75, 1.6, 0.0001, 8.5),
	FishEnum.BirchCrate : FishObject.new(FishEnum.BirchCrate,"Birch Crate", 						350, 1.2, 85, 3, 0.00016, 8),
	FishEnum.SpruceCrate : FishObject.new(FishEnum.SpruceCrate,"Spruce Crate",						400, 1.15, 95, 4.6, 0.00035, 7.5),
	FishEnum.ChestnutCrate : FishObject.new(FishEnum.ChestnutCrate,"Chestnut Crate", 				450, 1.1, 105, 6.6, 0.0006, 7.2),
	FishEnum.CherryCrate : FishObject.new(FishEnum.CherryCrate,"Cherry Crate",						500, 1.05, 115, 9.1, 0.00099, 6.9),
	FishEnum.AshCrate : FishObject.new(FishEnum.AshCrate,"Ash Crate",								550, 1, 125, 10, 0.002, 6.6),
	FishEnum.CedarCrate : FishObject.new(FishEnum.CedarCrate,"Cedar Crate", 						600, 0.95, 135, 12, 0.0029, 6.3),
	FishEnum.MahoganyCrate : FishObject.new(FishEnum.MahoganyCrate,"Mahogany Crate", 				650, 0.9, 145, 14, 0.0055, 6),
	FishEnum.EbonyCrate : FishObject.new(FishEnum.EbonyCrate,"Ebony Crate", 						700, 0.85, 155, 16, 0.0099, 5.7),
	FishEnum.DogwoodCrate : FishObject.new(FishEnum.DogwoodCrate,"Dogwood Crate",					750, 0.8, 165, 19, 0.019, 5.4),
	FishEnum.RosewoodCrate : FishObject.new(FishEnum.RosewoodCrate,"Rosewood Crate",				800, 0.75, 175, 24, 0.077, 5),
	FishEnum.GhostGumCrate : FishObject.new(FishEnum.GhostGumCrate,"Ghost Gum Crate",				850, 0.7, 185, 35, 0.2, 4.6),
	FishEnum.DragonwoodCrate : FishObject.new(FishEnum.DragonwoodCrate,"Dragonwood Crate",			900, 0.65, 195, 45, 0.6, 4.2),
	FishEnum.BlueWhale : FishObject.new(FishEnum.BlueWhale,"Blue Whale",							1500, 3.3, 75, 6, 0.0001, 7),
	FishEnum.MultiplyingFish : FishObject.new(FishEnum.MultiplyingFish,"Multiplying Fish",			777, 0.82, 80, 14, 0.001, 4),
}

var FishPrice = {
	FishEnum.Boot :  2,
	FishEnum.Seaweed : 1,
	FishEnum.ColaBottle : 2.5,
	FishEnum.Catfish : 5,
	FishEnum.GoldPotI : 15,
	FishEnum.GoldPotII : 90,
	FishEnum.GoldPotIII : 310,
	FishEnum.GoldFish : 1000,
	FishEnum.MagicPotI : 10,
	FishEnum.MagicPotII : 75,
	FishEnum.MagicPotIII : 290,
	FishEnum.MagicFish : 900,
	FishEnum.SpeedFish : 550,
	FishEnum.StorageBox : 35,
	FishEnum.ResearchFish : 2750,
	FishEnum.WoodFish : 730,
	FishEnum.DamFish : 3200,
	FishEnum.LuckyFish : 15000,
	FishEnum.CrateFish : 225,
	FishEnum.BotFish : 1100,
	FishEnum.IceFish : 2200,
	FishEnum.BaitFish : 666,
	FishEnum.ElectricEal : 200,
	FishEnum.ElectricJellyfish : 5000,
	FishEnum.ElectricSponge : 20000,
	FishEnum.ConstructionShark : 1111,
	FishEnum.SalmonLumberJack : 6666,
	FishEnum.AscentionFish : 320,
	FishEnum.DescentionFish : 12000,
	FishEnum.BigFish : 500,
	FishEnum.Clownfish : 10000,
	FishEnum.Stick : 400,
	FishEnum.OakCrate : 5,
	FishEnum.AppleCrate : 25,
	FishEnum.MapleCrate : 45,
	FishEnum.BirchCrate : 65,
	FishEnum.SpruceCrate : 85,
	FishEnum.ChestnutCrate : 350,
	FishEnum.CherryCrate : 400,
	FishEnum.AshCrate : 450,
	FishEnum.CedarCrate : 1000,
	FishEnum.MahoganyCrate : 1200,
	FishEnum.EbonyCrate : 3000,
	FishEnum.DogwoodCrate : 4000,
	FishEnum.RosewoodCrate : 5000,
	FishEnum.GhostGumCrate : 10000,
	FishEnum.DragonwoodCrate : 15000,
	FishEnum.BlueWhale : 22000,
	FishEnum.MultiplyingFish : 8500,
}

var FishLevel = {
	FishEnum.Boot :  0,
	FishEnum.Seaweed : 0,
	FishEnum.ColaBottle : 0,
	FishEnum.Catfish : 0,
	FishEnum.GoldPotI : 0,
	FishEnum.GoldPotII : 1,
	FishEnum.GoldPotIII : 1,
	FishEnum.GoldFish : 3,
	FishEnum.MagicPotI : 0,
	FishEnum.MagicPotII : 2,
	FishEnum.MagicPotIII : 2,
	FishEnum.MagicFish : 4,
	FishEnum.SpeedFish : 3,
	FishEnum.StorageBox : 0,
	FishEnum.ResearchFish : 5,
	FishEnum.WoodFish : 4,
	FishEnum.DamFish : 5,
	FishEnum.LuckyFish : 3,
	FishEnum.CrateFish : 2,
	FishEnum.BotFish : 4,
	FishEnum.IceFish : 5,
	FishEnum.BaitFish : 3,
	FishEnum.ElectricEal : 1,
	FishEnum.ElectricJellyfish : 1,
	FishEnum.ElectricSponge : 2,
	FishEnum.ConstructionShark : 3,
	FishEnum.SalmonLumberJack : 5,
	FishEnum.AscentionFish : 2,
	FishEnum.DescentionFish : 5,
	FishEnum.BigFish : 3,
	FishEnum.Clownfish : 5,
	FishEnum.Stick : 4,
	FishEnum.OakCrate : 0,
	FishEnum.AppleCrate : 1,
	FishEnum.MapleCrate : 1,
	FishEnum.BirchCrate : 1,
	FishEnum.SpruceCrate : 1,
	FishEnum.ChestnutCrate : 2,
	FishEnum.CherryCrate : 2,
	FishEnum.AshCrate : 2,
	FishEnum.CedarCrate : 3,
	FishEnum.MahoganyCrate : 3,
	FishEnum.EbonyCrate : 4,
	FishEnum.DogwoodCrate : 4,
	FishEnum.RosewoodCrate : 4,
	FishEnum.GhostGumCrate : 5,
	FishEnum.DragonwoodCrate : 5,
	FishEnum.BlueWhale : 5,
	FishEnum.MultiplyingFish : 4,
}

var FishRarity = {
	FishEnum.Boot :  50,
	FishEnum.Seaweed : 60,
	FishEnum.ColaBottle : 33,
	FishEnum.Catfish : 30,
	FishEnum.GoldPotI : 25,
	FishEnum.GoldPotII : 20,
	FishEnum.GoldPotIII : 15,
	FishEnum.GoldFish : 5,
	FishEnum.MagicPotI : 22,
	FishEnum.MagicPotII : 17,
	FishEnum.MagicPotIII : 12,
	FishEnum.MagicFish : 4,
	FishEnum.SpeedFish : 12,
	FishEnum.StorageBox : 10,
	FishEnum.ResearchFish : 15,
	FishEnum.WoodFish : 30,
	FishEnum.DamFish : 16,
	FishEnum.LuckyFish : 1,
	FishEnum.CrateFish : 25,
	FishEnum.BotFish : 40,
	FishEnum.IceFish : 19,
	FishEnum.BaitFish : 12,
	FishEnum.ElectricEal : 3,
	FishEnum.ElectricJellyfish : 2,
	FishEnum.ElectricSponge : 1,
	FishEnum.ConstructionShark : 7,
	FishEnum.SalmonLumberJack : 6,
	FishEnum.AscentionFish : 15,
	FishEnum.DescentionFish : 25,
	FishEnum.BigFish : 33,
	FishEnum.Clownfish : 26,
	FishEnum.Stick : 40,
	FishEnum.OakCrate : 20,
	FishEnum.AppleCrate : 20,
	FishEnum.MapleCrate : 20,
	FishEnum.BirchCrate : 20,
	FishEnum.SpruceCrate : 20,
	FishEnum.ChestnutCrate : 20,
	FishEnum.CherryCrate : 20,
	FishEnum.AshCrate : 20,
	FishEnum.CedarCrate : 20,
	FishEnum.MahoganyCrate : 20,
	FishEnum.EbonyCrate : 20,
	FishEnum.DogwoodCrate : 20,
	FishEnum.RosewoodCrate : 20,
	FishEnum.GhostGumCrate : 20,
	FishEnum.DragonwoodCrate : 20,
	FishEnum.BlueWhale : 5,
	FishEnum.MultiplyingFish : 15,
}

enum ShopItemEnum {
	NoBait,
	Worm,
	Cricket,
	Jig,
	Leech,
	WyvernsFeather,
	Autoclicker1,
	Autoclicker2,
	Autoclicker3,
	WpsBonus1,
	WpsBonus2,
	WpsBonus3,
	WpcBonus1,
	WpcBonus2,
	WpcBonus3,
	WpsIncrease,
	WpcIncrease,
	StorageIncrease,
	ResearchSlot,
	FishingChance1,
	FishingChance2,
	ChanceToUseBait,
}

var ShopItems = {
	ShopItemEnum.Worm : {
		"Name" : "Worm",
		"Description" : "Worm",
		"Price" : 1,
		"UnlockPrice" : 1,
		"FishingPower" : 1,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Cricket : {
		"Name" : "Cricket",
		"Description" : "Cricket",
		"Price" : 35,
		"UnlockPrice" : 350,
		"FishingPower" : 2,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Jig : {
		"Name" : "Jig",
		"Description" : "Jig",
		"Price" : 150,
		"UnlockPrice" : 1500,
		"FishingPower" : 3,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Leech : {
		"Name" : "Leech",
		"Description" : "Leech",
		"Price" : 2,
		"UnlockPrice" : 2,
		"FishingPower" : 4,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.WyvernsFeather : {
		"Name" : "Wyverns Feather",
		"Description" : "Wyverns Feather",
		"Price" : 3000,
		"UnlockPrice" : 30000,
		"FishingPower" : 5,
		"IsBait" : true,
		"HasCount" : true,
	},
	ShopItemEnum.Autoclicker1 : {
		"Name" : "+1 Autoclicker",
		"Description" : "Add another Autoclicker",
		"Price" : 1000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.Autoclicker2 : {
		"Name" : "+1 Autoclicker",
		"Description" : "Add another Autoclicker",
		"Price" : 50000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.Autoclicker3 : {
		"Name" : "+1 Autoclicker",
		"Description" : "Add another Autoclicker",
		"Price" : 250000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsBonus1 : {
		"Name" : "WPS Bonus 1",
		"Description" : "10% Wood Per Second Bonus For 10 minutes",
		"Price" : 300,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsBonus2 : {
		"Name" : "WPS Bonus 2",
		"Description" : "20% Wood Per Second Bonus For 20 minutes",
		"Price" : 6000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsBonus3 : {
		"Name" : "WPS Bonus 3",
		"Description" : "30% Wood Per Second Bonus For 30 minutes",
		"Price" : 90000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpcBonus1 : {
		"Name" : "WPC Bonus 1",
		"Description" : "30% Wood Per Click Bonus For 10 minutes",
		"Price" : 300,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpcBonus2 : {
		"Name" : "WPC Bonus 2",
		"Description" : "60% Wood Per Click Bonus For 20 minutes",
		"Price" : 6000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpcBonus3 : {
		"Name" : "WPC Bonus 3",
		"Description" : "90% Wood Per Click Bonus For 30 minutes",
		"Price" : 90000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.WpsIncrease : {
		"Name" : "Increase WPS",
		"Description" : "Increase Wood Per Second By 1%",
		"Price" : 5,
		"IsBait" : false,
		"HasCount" : true,
	},
	ShopItemEnum.WpcIncrease : {
		"Name" : "Increase WPC",
		"Description" : "Increase Wood Per Click By 1%",
		"Price" : 7,
		"IsBait" : false,
		"HasCount" : true,
	},
	ShopItemEnum.StorageIncrease : {
		"Name" : "Increase Storage",
		"Description" : "Increase Storage By 1%",
		"Price" : 10,
		"IsBait" : false,
		"HasCount" : true,
	},
	ShopItemEnum.ResearchSlot : {
		"Name" : "+1 Research Slot",
		"Description" : "Add another Research Slot",
		"Price" : 7500,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingChance1 : {
		"Name" : "+1 Fishing Chance",
		"Description" : "Add another Fishing Chance",
		"Price" : 1000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.FishingChance2 : {
		"Name" : "+1 Fishing Chance",
		"Description" : "Add another Fishing Chance",
		"Price" : 7000,
		"IsBait" : false,
		"HasCount" : false,
	},
	ShopItemEnum.ChanceToUseBait : {
		"Name" : "Lower Bait Use",
		"Description" : "Lower Chance Bait Is Used By 10%",
		"Price" : 100,
		"IsBait" : false,
		"HasCount" : true,
	},
}

enum FishEnum {
	Boot,
	Seaweed,
	ColaBottle,
	Catfish,
	GoldPotI,
	GoldPotII,
	GoldPotIII,
	GoldFish,
	MagicPotI,
	MagicPotII,
	MagicPotIII,
	MagicFish,
	SpeedFish,
	StorageBox,
	ResearchFish,
	WoodFish,
	DamFish,
	LuckyFish,
	CrateFish,
	BotFish,
	IceFish,
	BaitFish,
	ElectricEal,
	ElectricJellyfish,
	ElectricSponge,
	ConstructionShark,
	SalmonLumberJack,
	AscentionFish,
	DescentionFish,
	BigFish,
	Clownfish,
	Stick,
	OakCrate,
	AppleCrate,
	MapleCrate,
	BirchCrate,
	SpruceCrate,
	ChestnutCrate,
	CherryCrate,
	AshCrate,
	CedarCrate,
	MahoganyCrate,
	EbonyCrate,
	DogwoodCrate,
	RosewoodCrate,
	GhostGumCrate,
	DragonwoodCrate,
	BlueWhale,
	MultiplyingFish,
}
