extends Node

var Research = {
	"1" : {
		"Name" : "Unlock Woodcamps",
		"Description" : "Allows building woodcamps, unlocks woodcamp upgrades",
		"Time" : 60, # Seconds
		"OakCost" : 4000,
		"AppleCost" : 1000,
		"MapleCost" : 0,
		"BirchCost" : 0,
		"SpruceCost" : 0,
		"ChestnutCost" : 0,
		"CherryCost" : 0,
		"AshCost" : 0,
		"CedarCost" : 0,
		"MahoganyCost" : 0,
		"EbonyCost" : 0,
		"DogwoodCost" : 0,
		"RosewoodCost" : 0,
		"Ghost GumCost" : 0,
		"DragonwoodCost" : 0,
	},
	"2" :  {
		"Name" : "Unlock Maple Wood",
		"Description" : "Maple Yum!",
		"Time" : 180, # Seconds
		"OakCost" : 7000,
		"AppleCost" : 3000,
		"MapleCost" : 0,
		"BirchCost" : 0,
		"SpruceCost" : 0,
		"ChestnutCost" : 0,
		"CherryCost" : 0,
		"AshCost" : 0,
		"CedarCost" : 0,
		"MahoganyCost" : 0,
		"EbonyCost" : 0,
		"DogwoodCost" : 0,
		"RosewoodCost" : 0,
		"Ghost GumCost" : 0,
		"DragonwoodCost" : 0,
	},
	"3" :  {
		"Name" : "Double Classic Storage",
		"Description" : "Doubles Storage for all Classic Wood",
		"Time" : 360, # Seconds
		"OakCost" : 11000,
		"AppleCost" : 6000,
		"MapleCost" : 1000,
		"BirchCost" : 0,
		"SpruceCost" : 0,
		"ChestnutCost" : 0,
		"CherryCost" : 0,
		"AshCost" : 0,
		"CedarCost" : 0,
		"MahoganyCost" : 0,
		"EbonyCost" : 0,
		"DogwoodCost" : 0,
		"RosewoodCost" : 0,
		"Ghost GumCost" : 0,
		"DragonwoodCost" : 0,
	},
}
