extends Node

var UpgradePositions = {
	"Oak" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Apple" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Maple" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Birch" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Spruce" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Chestnut" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Cherry" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Ash" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Cedar" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Mahogany" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Ebony" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Dogwood" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Rosewood" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Ghost Gum" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Dragonwood" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
	"Gold" : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
}

var Upgrades = {
	"Oak" : {
		"1" : {
			"Name" : "+0.3 Oak Per Beaver",
			"Description" : "Increases base Oak gathered per Beaver by +0.3",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+100 Oak Storage",
			"Description" : "Increases base Oak storage capacity by 100",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "Unlock Apple Wood",
			"SecondaryName" : "10% Cheaper Beavers",
			"Description" : "Unlocks Apple wood for production",
			"SecondaryDescription" : "10% Cheaper Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : " +0.5 Woodcamp WPS",
			"Description" : "Increases The Oak woodcamp base wood gain by 0.5",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Oak"]["Woodcamps"] > 0,
		},
		"5" :  {
			"Name" : "6.5% More Storage",
			"Description" : "6.5% More Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+1 Beaver Per 5 WC's",
			"Description" : "+1 Beaver Per 5 WC's",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Oak"]["Woodcamps"] > 0,
		},
		"7" :  {
			"Name" : "+0.005 Oak Price",
			"Description" : "+0.005 Oak Price",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Unlocked"],
		},
		"8" :  {
			"Name" : "All Upgrades 6% Cheaper",
			"Description" : "Make All Upgrades 6% Cheaper",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 5,
		},
		"9" :  {
			"Name" : "5% Global Wood Price",
			"Description" : "5% Global Wood Price",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Unlocked"],
			"MagicCost" : 8,
		},
		"10" :  {
			"Name" : "3.5% Faster Research",
			"Description" : "3.5% Faster Research",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Research"]["Unlocked"],
			"MagicCost" : 25,
		},
	},
	"Apple" : {
		"1" : {
			"Name" : "+0.35 Apple Per Beaver",
			"Description" : "+0.35 Apple Per Beaver",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+110 Apple Storage",
			"Description" : "Increases base Apple storage capacity by 110",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "Unlock Research",
			"SecondaryName" : "7.5% More Storage",
			"Description" : "Unlocks Research",
			"SecondaryDescription" : "7.5% More Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "+1 Woodcamp WPS",
			"Description" : "+1 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Apple"]["Woodcamps"] > 0,
		},
		"5" :  {
			"Name" : "Oak WPS 11.5%",
			"Description" : "Oak WPS 11.5%",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Apple"]["Woodcamps"] > 0,
		},
		"6" :  {
			"Name" : "+4.5% WPS",
			"Description" : "+4.5% WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Apple"]["Woodcamps"] > 0,
		},
		"7" :  {
			"Name" : "WC Uses 1.25% Less Wood",
			"Description" : "Apple woodcamps use 1.25% less lower tier wood",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Apple"]["Woodcamps"] > 0,
		},
		"8" :  {
			"Name" : "Global WPS 2.5%",
			"Description" : "Increases Global Wood Per Second By 2.5%",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 10,
		},
		"9" :  {
			"Name" : "Global Storage 1.85%",
			"Description" : "Increases Global Storage By 1.85%",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 50,
		},
		"10" :  {
			"Name" : "+5% Fish Price",
			"Description" : "+5% Fish Price",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 150,
		},
	},
	"Maple" : {
		"1" : {
			"Name" : "+0.4 Maple Per Beaver",
			"Description" : "Increases base Maple gathered by Beaver by 0.4",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+120 Maple Storage",
			"Description" : "Increases base Maple storage capacity by 120",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+1.5 Woodcamp WPS",
			"Description" : "+1.5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Maple"]["Woodcamps"] > 0,
		},
		"4" :  {
			"Name" : "7% Cheaper WC",
			"Description" : "7% Cheaper WC",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Maple"]["Woodcamps"] > 0,
		},
		"5" :  {
			"Name" : "+9.5% WC Storage",
			"Description" : "+9.5% WC Storage",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Maple"]["Woodcamps"] > 0,
		},
		"6" :  {
			"Name" : "4.5% WPC to WPS",
			"Description" : "4.5% WPC to WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Maple"]["Woodcamps"] > 0,
		},
		"7" :  {
			"Name" : "9% Cheaper Global Beavers",
			"Description" : "9% Cheaper Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "Merchants Sell 4% More",
			"Description" : "Merchants Sell 4% More",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Bots"]["Unlocked"],
			"MagicCost" : 50,
		},
		"9" :  {
			"Name" : "+0.05 Global WPS",
			"Description" : "+0.05 Global WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Maple"]["Woodcamps"] > 0,
			"MagicCost" : 250,
		},
		"10" :  {
			"Name" : "3% More Magic",
			"Description" : "3% More Magic",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Magic"]["Ascention"],
			"MagicCost" : 750,
		},
	},
	"Birch" : {
		"1" : {
			"Name" : "+0.45 Birch Per Beaver",
			"Description" : "Increases base Birch gathered by Beaver by 0.45",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+130 Birch Storage",
			"Description" : "Increases base Birch storage capacity by 130",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+2 Woodcamp WPS",
			"Description" : "+2 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Birch"]["Woodcamps"] > 0,
		},
		"4" :  {
			"Name" : "+100 Storage Per Beaver",
			"Description" : "+100 Storage Per Beaver",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "+4% WPS",
			"Description" : "+4% WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Birch"]["Woodcamps"] > 0,
		},
		"6" :  {
			"Name" : "+3.3% Storage",
			"Description" : "+3% Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "Maple WPS 3.5%",
			"Description" : "Increases Produced Maple Wood Per Second By 3.5%",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "Fish 0.25% Slower",
			"Description" : "Fish Become 0.25% Slower",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 150,
		},
		"9" :  {
			"Name" : "3% Cheaper Merchants",
			"Description" : "3% Cheaper Merchants",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Bots"]["Unlocked"],
			"MagicCost" : 750,
		},
		"10" :  {
			"Name" : "+4% Dam Construction Speed",
			"Description" : "+4% Dam Construction Speed",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["Unlocked"],
			"MagicCost" : 2500,
		},
	},
	"Spruce" : {
		"1" : {
			"Name" : "+0.5 Birch Per Beaver",
			"Description" : "Increases base Spruce gathered by Beaver by 0.5",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+140 Spruce storage",
			"Description" : "Increases base Spruce storage capacity by 140",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+2.5 Woodcamp WPS",
			"Description" : "+2.5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Spruce"]["Woodcamps"] > 0,
		},
		"4" :  {
			"Name" : "6% More Storage",
			"Description" : "6% More Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "+2.5% WPS",
			"Description" : "+2.5% WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Spruce"]["Woodcamps"] > 0,
		},
		"6" :  {
			"Name" : "+0.75% WPC Per WC",
			"Description" : "+0.75% WPC Per WC",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Spruce"]["Woodcamps"] > 0,
		},
		"7" :  {
			"Name" : "WC Uses 1.95% Less Wood",
			"Description" : "Spruce Woodcamps Use 1.95% Less Wood For Production",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Spruce"]["Woodcamps"] > 0,
		},
		"8" :  {
			"Name" : "+25 Wood Sold Per Merchant",
			"Description" : "+25 Wood Sold Per Merchant",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Bots"]["Unlocked"],
			"MagicCost" : 400,
		},
		"9" :  {
			"Name" : "Fish Stay 0.25% Longer",
			"Description" : "Fish Stay 0.65% Longer",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 1200,
		},
		"10" :  {
			"Name" : "+5% Dam Construction Speed",
			"Description" : "+5% Dam Construction Speed",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["Unlocked"],
			"MagicCost" : 3500,
		},
	},
	"Chestnut" : {
		"1" : {
			"Name" : "+0.55 Chestnut Per Beaver",
			"Description" : "Increases base Chestnut gathered by Beaver by 0.55",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+150 Chestnut Storage",
			"Description" : "Increases base Chestnut storage capacity by 150",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+3 Woodcamp WPS",
			"Description" : "+3 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Chestnut"]["Woodcamps"] > 0,
		},
		"4" :  {
			"Name" : "+5% WC Effects",
			"Description" : "+5% WC Effects",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Chestnut"]["Woodcamps"] > 0,
		},
		"5" :  {
			"Name" : "3% WPC To WPS",
			"Description" : "3% WPC To WPS",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Chestnut"]["Woodcamps"] > 0,
		},
		"6" :  {
			"Name" : "+1 Beaver Per 5 WC's",
			"Description" : "+1 Beaver Per 5 WC's",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Chestnut"]["Woodcamps"] > 0,
		},
		"7" :  {
			"Name" : "+0.35 Chestnut Price",
			"Description" : "+0.35 Chestnut Price",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Unlocked"],
		},
		"8" :  {
			"Name" : "Global WPC +0.75% Per WC",
			"Description" : "Increases Global Wood Per Second By +0.75% Per Each Chestnut Woodcamp",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"] and SaveData.Resources["Chestnut"]["Woodcamps"] > 0,
			"MagicCost" : 1000,
		},
		"9" :  {
			"Name" : "2.85% Cheaper Gold Upgrades",
			"Description" : "0.85% Cheaper Gold Upgrades",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 5000,
		},
		"10" :  {
			"Name" : "5% More Magic",
			"Description" : "5% More Magic",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Magic"]["Ascention"],
			"MagicCost" : 15000,
		},
	},
	"Cherry" : {
		"1" : {
			"Name" : "+0.6 Cherry Per Beaver",
			"Description" : "Increases base Cherry gathered by Beaver by 0.6",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+160 Cherry Storage",
			"Description" : "Increases base Cherry storage capacity by 160",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+3.5 Woodcamp WPS",
			"Description" : "+3.5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "7.5% WPC To WPS",
			"Description" : "7.5% WPC To WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "11% Cheaper Beavers",
			"Description" : "11% Cheaper Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+2.5% Cherry Price",
			"Description" : "+2.5% Cherry Wood Price",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "10% More Storage",
			"Description" : "10% More Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "2.2% Faster Research",
			"Description" : "2.2% Faster Research",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 5000,
		},
		"9" :  {
			"Name" : "+0.45% Fish Size",
			"Description" : "+0.45% Fish Size",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 25000,
		},
		"10" :  {
			"Name" : "+4.5% WPS Per Dam Section",
			"Description" : "+4.5% More WPS Per Dam Section",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["AnySectionCompleted"],
			"MagicCost" : 7.5e9,
		},
	},
	"Ash" : {
		"1" : {
			"Name" : "+0.65 Ash Per Beaver",
			"Description" : "Increases base Ash gathered by Beaver by 0.65",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+170 Ash Storage",
			"Description" : "Increases base Ash storage capacity by 170",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+4 Woodcamp WPS",
			"Description" : "+4 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "9.5% Storage From WC",
			"Description" : "9.5% Storage From WC",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "2.9% WPS",
			"Description" : "2.9% WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+1 Beaver Per 13 Cherry Beavers",
			"Description" : "+1 Beaver Per 13 Cherry Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "5% Cheaper Upgrades",
			"Description" : "5% Cheaper Upgrades",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "1.75% Research Time",
			"Description" : "Research Takes 1.75% Less Time To Research",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 12500,
		},
		"9" :  {
			"Name" : "+3.3% Global Wood Price",
			"Description" : "+3.3% Global Wood Price",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 75000,
		},
		"10" :  {
			"Name" : "0.55% More Fish",
			"Description" : "0.55% More Fish",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 250000,
		},
	},
	"Cedar" : {
		"1" : {
			"Name" : "+0.7 Cedar Per Beaver",
			"Description" : "Increases base Cedar gathered by Beaver by 0.7",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+180 Cedar Storage",
			"Description" : "Increases base Cedar storage capacity by 180",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+4.5 Woodcamp WPS",
			"Description" : "+4.5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "+1 Beaver Per 8 WC's",
			"Description" : "+1 Beaver Per 8 WC's",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "+0.5% Storage Per Beaver",
			"Description" : "+0.5% Storage Per Beaver",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "7% Cheaper WC's",
			"Description" : "7% Cheaper WC's",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "0.3% WPC To WPS",
			"Description" : "0.3% WPC To WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "+0.45% Global Wood Price",
			"Description" : "+0.45% Global Wood Price",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 75000,
		},
		"9" :  {
			"Name" : "3.5% More Magic",
			"Description" : "3.5% More Magic",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Magic"]["Ascention"],
			"MagicCost" : 550000,
		},
		"10" :  {
			"Name" : "4% Cheaper WC Globaly",
			"Description" : "4% Cheaper WC Globaly",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 3750000,
		},
	},
	"Mahogany" : {
		"1" : {
			"Name" : "+0.75 Mahogany Per Beaver",
			"Description" : "Increases base Mahogany gathered by Beaver by 0.75",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+190 Mahogany Storage",
			"Description" : "Increases base Mahogany storage capacity by 190",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+5 Woodcamp WPS",
			"Description" : "+5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "5% Cheaper Beavers",
			"Description" : "5% Cheaper Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "+1 WC Per 10 Beavers",
			"Description" : "+1 WC Per 10 Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+5.5% WC Storage",
			"Description" : "+5.5% WC Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "Classic WPS +0.1%",
			"Description" : "Classic WPS +0.1%",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "+0.6% Global WPS",
			"Description" : "+0.6% Global WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 200000,
		},
		"9" :  {
			"Name" : "+5% WPC Per Dam Section",
			"Description" : "+5% More WPC Per Dam Section",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["AnySectionCompleted"],
			"MagicCost" : 2e6,
		},
		"10" :  {
			"Name" : "Chance Bait Used -0.25%",
			"Description" : "+0.25%% Chance That Bait Is Not Used When Fishing",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 5.5e9,
		},
	},
	"Ebony" : {
		"1" : {
			"Name" : "+0.8 Ebony Per Beaver",
			"Description" : "Increases base Ebony gathered by Beaver by 0.8",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+200 Ebony Storage",
			"Description" : "Increases base Ebony storage capacity by 200",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+5.5 Woodcamp WPS",
			"Description" : "+5.5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "+1 WC Per 8 Beavers",
			"Description" : "+1 WC Per 8 Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "1.5% WPC To WPS",
			"Description" : "1.5% WPC TO WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+1 Beaver Per 5 WC's",
			"Description" : "+1 Beaver Per 5 WC's",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "+750 Ebony Price",
			"Description" : "+750 Ebony Price",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "2% Slower Fish",
			"Description" : "2% Slower Fish",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 5000000,
		},
		"9" :  {
			"Name" : "5% Cheaper Merchants",
			"Description" : "5% Cheaper Merchants",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Bots"]["Unlocked"],
			"MagicCost" : 9.5e7,
		},
		"10" :  {
			"Name" : "+0.27% Global WPS",
			"Description" : "+0.27% Global WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 1e10,
		},
	},
	"Dogwood" : {
		"1" : {
			"Name" : "+0.85 Dogwood Per Beaver",
			"Description" : "Increases base Dogwood gathered by Beaver by 0.85",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+210 Dogwood Storage",
			"Description" : "Increases base Dogwood storage capacity by 210",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+6 Woodcamp WPS",
			"Description" : "+6 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "0.75% WPC To WPS",
			"Description" : "0.75% WPC To WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "WC's Use 3% Less Wood",
			"Description" : "WC's Use 3% Less Wood",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+3% Storage Per Beaver",
			"Description" : "+3% Storage Per Beaver",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "+6% WPC",
			"Description" : "+6% WPC",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "Merchants Sell 5% More Wood",
			"Description" : "Merchants Sell 5% More Wood",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Bots"]["Unlocked"],
			"MagicCost" : 9e6,
		},
		"9" :  {
			"Name" : "+7.5% Fish Price",
			"Description" : "+7.5% Fish Price",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Fishing"]["Unlocked"],
			"MagicCost" : 6e8,
		},
		"10" :  {
			"Name" : "+6% Storage Per Dam Section",
			"Description" : "+6% More Storage Per Dam Section",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["AnySectionCompleted"],
			"MagicCost" : 2e10,
		},
	},
	"Rosewood" : {
		"1" : {
			"Name" : " +0.9 Rosewood Per Beaver",
			"Description" : "Increases base Rosewood gathered by Beaver by 0.9",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+220 Rosewood Storage",
			"Description" : "Increases base Rosewood storage capacity by 220",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+6.5 Woodcamp WPS",
			"Description" : "+6.5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "20% Cheaper Beavers",
			"Description" : "20% Cheaper Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "2% More Storage",
			"Description" : "2% More Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "0.2% WPS Per Beaver",
			"Description" : "0.2% WPS Per Beaver",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "+300 Storage Per Beaver",
			"Description" : "+300 Storage Per Beaver",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "0.3% Faster Research",
			"Description" : "0.3% Faster Research",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 2.5e7,
		},
		"9" :  {
			"Name" : "+0.07% Global WPS",
			"Description" : "+0.07% Global WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 1.3e9,
		},
		"10" :  {
			"Name" : "+6% Dam Construction Speed",
			"Description" : "+6% Dam Construction Speed",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["Unlocked"],
			"MagicCost" : 3.5e10,
		},
	},
	"Ghost Gum" : {
		"1" : {
			"Name" : "+0.95 Ghost Gum Per Beaver",
			"Description" : "Increases base Ghost Gum gathered by Beaver by 0.95",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+230 Ghost Gum Storage",
			"Description" : "Increases base Ghost Gum storage capacity by 230",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+7 Woodcamp WPS",
			"Description" : "+7 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "Beaver Gets +0.5 Wood Per WC",
			"Description" : "Beaver Gets +0.5 Wood Per Woodcamp",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "7% Cheaper Woodcamps",
			"Description" : "7% Cheaper Woodcamps",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+7% Storage From WC",
			"Description" : "+7% Storage From WC",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "+1 WC Per 7 Beavers",
			"Description" : "+1 WC Per 7 Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "+4% Global Wood Price",
			"Description" : "+4% Global Wood Price",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 4e9,
		},
		"9" :  {
			"Name" : "+2% Global Storage",
			"Description" : "+2% Global Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 1.1e10,
		},
		"10" :  {
			"Name" : "+7% Dam Construction Speed",
			"Description" : "+7% Dam Construction Speed",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["Unlocked"],
			"MagicCost" : 6.6e10,
		},
	},
	"Dragonwood" : {
		"1" : {
			"Name" : "+1 Dragonwood Per Beaver",
			"Description" : "Increases base Dragonwood gathered by Beaver by 1",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "+240 Dragonwood Storage",
			"Description" : "Increases base Dragonwood storage capacity by 240",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"3" :  {
			"Name" : "+7.5 Woodcamp WPS",
			"Description" : "+7.5 Woodcamp WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "WC Uses 1.5% Less Wood",
			"Description" : "WC Uses 1.5% Less Wood",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "+8% WPS",
			"Description" : "+8% WPS",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "+2.5% Storage Per Beaver",
			"Description" : "+2.5% Storage Per Beaver",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "+1 Beaver Per 10 WC's",
			"Description" : "+1 Beaver Per 10 WC's",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "+7.5% Effect Per Dam Section",
			"Description" : "+7.5% More WPS, WPC, Storage Per Dam Section",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["AnySectionCompleted"],
			"MagicCost" : 3e10,
		},
		"9" :  {
			"Name" : "3% Cheaper Global Upgrades",
			"Description" : "3% Cheaper Global Upgrades",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 1e11,
		},
		"10" :  {
			"Name" : "2.5% More Magic",
			"Description" : "2.5% More Magic",
			"OtherText" : "",
			"Unlocked" : func(): return true,
			"MagicCost" : 5.5e11,
		},
	},
	"Gold" : {
		"1" : {
			"Name" : "1% Better Beavers",
			"Description" : "1% Better Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"2" :  {
			"Name" : "1% Better Woodcamps",
			"Description" : "1% Better Woodcamps",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Woodcamps"]["Unlocked"],
		},
		"3" :  {
			"Name" : "1% More Storage",
			"Description" : "1% More Storage",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"4" :  {
			"Name" : "1% Faster Research",
			"Description" : "1% Faster Research",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"5" :  {
			"Name" : "1% Wood Price",
			"Description" : "1% Wood Price",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"6" :  {
			"Name" : "1% Cheaper Beavers",
			"Description" : "1% Cheaper Beavers",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"7" :  {
			"Name" : "1% Cheaper Woodcamps",
			"Description" : "1% Cheaper Woodcamps",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"8" :  {
			"Name" : "1% More Magic",
			"Description" : "1% More Magic",
			"OtherText" : "",
			"Unlocked" : func(): return true,
		},
		"9" :  {
			"Name" : "1% Merchant Price",
			"Description" : "1% Merchant Price",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Market"]["Bots"]["Unlocked"],
		},
		"10" :  {
			"Name" : "+1% Dam Construction Speed",
			"Description" : "+1% Dam Construction Speed",
			"OtherText" : "",
			"Unlocked" : func(): return Unlocks.Unlocks["Dams"]["Unlocked"],
		},
	},
}
