extends Node

var lastTimeSaved
var timePlayed

var level = 14

var Upgrades = {
	"Oak" : {
		"1" : {
			"Level" : 1,
		},
		"2" :  {
			"Level" : 1,
		},
		"3" :  {
			"Level" : 1,
		},
		"4" :  {
			"Level" : 1,
		},
		"5" :  {
			"Level" : 1,
		},
		"6" :  {
			"Level" : 1,
		},
		"7" :  {
			"Level" : 1,
		},
		"8" :  {
			"Level" : 1,
		},
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Apple" : {
		"1" : {
			"Level" : 1,
		},
		"2" :  {
			"Level" : 1,
		},
		"3" :  {
			"Level" : 1,
		},
		"4" :  {
			"Level" : 1,
		},
		"5" :  {
			"Level" : 1,
		},
		"6" :  {
			"Level" : 1,
		},
		"7" :  {
			"Level" : 1,
		},
		"8" :  {
			"Level" : 1,
		},
		"9" :  {
			"Level" : 1,
		},
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Maple" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Birch" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Spruce" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Chestnut" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Cherry" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Ash" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Cedar" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Mahogany" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Ebony" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Dogwood" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Rosewood" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Ghost Gum" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
	"Dragonwood" : {
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
		"11" : false,
		"12" : false,
		"13" : false,
		"14" : false,
		"15" : false,
		"16" : false,
		"17" : false,
		"18" : false,
	},
}
