extends Node

var OriginalUnlocks

func _process(delta: float) -> void:
	pass
	#checkForUnlocks()

func checkForUnlocks():
	if SaveData.Resources["Oak"]["Count"] > 5:
		Unlocks["Oak"]["1"]["Unlocked"] = true
	if SaveData.Resources["Oak"]["Count"] > 15:
		Unlocks["Oak"]["2"]["Unlocked"] = true

var Unlocks = {
	"Oak" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Apple" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Maple" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Birch" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Spruce" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Chestnut" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Cherry" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Ash" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Cedar" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Mahogany" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Ebony" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Dogwood" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Rosewood" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Ghost Gum" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Dragonwood" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Gold" : {
		"Unlocked" : true,
		"ButtonBuyMax" : false,
		"PageBuyMax" : false,
		"1" : false,
		"2" : false,
		"3" : false,
		"4" : false,
		"5" : false,
		"6" : false,
		"7" : false,
		"8" : false,
		"9" : false,
		"10" : false,
	},
	"Upgrades" : {
		"ClassicBuyMax" : false,
		"RareBuyMax" : false,
		"MythicBuyMax" : false,
		"KeepClassicUpgrades" : false,
		"KeepRareUpgrades" : false,
		"KeepMythicUpgrades" : false,
		"KeepGoldUpgrades" : false,
	},
	"Woodcamps" : {
		"Unlocked" : false,
		"BuyMax" : false,
	},
	"Beavers" : {
		"Unlocked" : false,
		"BuyMax" : false,
	},
	"Research" : {
		"Unlocked" : false,
		"History" : false,
		"AutoResearch" : false,
		"ResearchItems" : {},
	},
	"Market" : {
		"Unlocked" : false,
		"Bots" : {
			"Unlocked" : false,
			"10x Buy" : false,
			"100x Buy" : false,
			"1000x Buy" : false,
		},
	},
	"Magic" : {
		"Ascention" : false,
		"Upgrades" : false,
		"PasiveGain" : false,
		"MagicItems" : {},
	},
	"Dams" : {
		"Unlocked" : false,
		"Small Dam" : {
			"Unlocked" : false,
			"Slot1" : false,
			"Slot2" : false,
			"Slot3" : false,
		},
		"Medium Dam" : {
			"Unlocked" : false,
			"Slot1" : false,
			"Slot2" : false,
			"Slot3" : false,
		},
		"Big Dam" : {
			"Unlocked" : false,
			"Slot1" : false,
			"Slot2" : false,
			"Slot3" : false,
		},
		"Giant Dam" : {
			"Unlocked" : false,
			"Slot1" : false,
			"Slot2" : false,
			"Slot3" : false,
		},
		"Mega Dam" : {
			"Unlocked" : false,
			"Slot1" : false,
			"Slot2" : false,
			"Slot3" : false,
		},
	},
	"Achievements" : {
		"Unlocked" : false,
		"AllAchievementsVisible" : false,
		"UnlockedAchievements" : {},
	},
	"Fishing" : {
		"Unlocked" : false,
		"Bait" : {
			"Unlocked" : false,
			"1" : false,
			"2" : false,
			"3" : false,
			"4" : false,
			"5" : false,
			"6" : false,
			"7" : false,
			"8" : false,
			"9" : false,
			"WoodBait" : false,
		},
		"Spot" : {
			"1" : false,
			"2" : false,
			"3" : false,
			"4" : false,
			"5" : false,
		},
	},
	"Storage" : {
		"Overloading" : false,
		"Unlimited" : false,
	},
}
