extends Node

var CurrentSaveName

var WoodTypes = ["Oak", "Apple", "Maple", "Birch", "Spruce",
				 "Chestnut", "Cherry", "Ash", "Cedar", "Mahogany",
				 "Ebony", "Dogwood", "Rosewood", "Ghost Gum", "Dragonwood",]

var ResourceValues = {
	"Fish" : {
		"PriceMultip": 1,
		"FishingWoodMultip" : 1,
		"MoreFishMultip" : 1,
		"BetterFishMultip" : 1,
		"LongerFishMultip" : 1,
		"FishEffectMultip" : 1,
		"BaitMultip" : 1,
		"BaitPriceMultip" : 1,
	},
	"Research" : {
		"TimeMultip": 1,
		"CostMultip" : 1,
	},
	"Gold" : {
		"PerSecond": 0,
		"GainMultip": 1,
		"UpgradeEffectMultip": 1,
		"UpgradePriceMultip": 1,
		"Color" : Color(0.877, 0.761, 0.412),
		"SecondaryColor" : Color(0.64, 0.54, 0.221),
	},
	"Magic" : {
		"GainMultip": 1,
		"EffectMultip" : 1,
		"PriceMultip" : 1,
		"PerSecondMultip" : 1,
		"UpgradePriceMultip" : 1,
		"PotentialMagic" : 0,
	},
	"Dam" : {
		"EffectMultip": 1,
		"PriceMultip" : 1,
		"MaterialsNeededMultip" : 1,
		"ConstructionSpeedMultip" : 1,
		"GoldGainMultip" : 1,
		"WoodGainMultip" : 1,
	},
	"Oak" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 100,
		"Color" : Color(0.258, 0.155, 0.086),
		"SecondaryColor" : Color(0.316, 0.262, 0.086),
		"RealPerSecondIncrease": 0, # calculated based on how full / empty this, previous and next wood type's storage is
		"RealPerSecondLoss": 0, # calculated based on how full / empty this, previous and next wood type's storage is
		"SoldFor": 0.015,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Apple" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.788, 0.368, 0.299),
		"SecondaryColor" : Color(0.424, 0.168, 0.127),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 0.06,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Maple" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.726, 0.611, 0.246),
		"SecondaryColor" : Color(0.318, 0.261, 0.079),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 0.15,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Birch" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.775, 0.614, 0.484),
		"SecondaryColor" : Color(0.282, 0.2, 0.132),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 0.35,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Spruce" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.255, 0.156, 0.087),
		"SecondaryColor" : Color(0.182, 0.106, 0.053),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 0.82,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Chestnut" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.589, 0.359, 0.156),
		"SecondaryColor" : Color(0.303, 0.174, 0.059),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 1.79,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Cherry" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.702, 0.247, 0.047),
		"SecondaryColor" : Color(0.31, 0.09, 0.008),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 3.90,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Ash" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.831, 0.824, 0.89),
		"SecondaryColor" : Color(0.354, 0.338, 0.455),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 8.6,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Cedar" : {
		"PerClick" : 100000000,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.608, 0.235, 0),
		"SecondaryColor" : Color(0.319, 0.109, 0),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 19,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Mahogany" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.299, 0.143, 0.028),
		"SecondaryColor" : Color(0.221, 0.1, 0.015),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 48,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Ebony" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.168, 0.153, 0.193),
		"SecondaryColor" : Color(0.12, 0.109, 0.14),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 115,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Dogwood" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.477, 0.614, 0.645),
		"SecondaryColor" : Color(0.208, 0.295, 0.314),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 260,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Rosewood" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.457, 0.236, 0.244),
		"SecondaryColor" : Color(0.306, 0.148, 0.154),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 600,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Ghost Gum" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.948, 0.599, 0.77),
		"SecondaryColor" : Color(0.473, 0.105, 0.322),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 1399,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
	"Dragonwood" : {
		"PerClick" : 100,
		"PerSecondIncrease": 0,
		"PerSecondLoss": 0,
		"Storage" : 1000,
		"Color" : Color(0.471, 0.533, 0.145),
		"SecondaryColor" : Color(0.27, 0.308, 0.069),
		"RealPerSecondIncrease": 0,
		"RealPerSecondLoss": 0,
		"SoldFor": 4000,
		"UpgradePriceMultip": 1,
		"WcPriceMultip": 1,
		"BeaverPriceMultip": 1,
		"BotPriceMultip": 1,
		"BotBaseSell": 1,
		"WoodSoldPerSecond": 10,
		"GoldGainPerSecond": 10, # from bots selling
	},
}
